export const defaultTheme = {
  colors: {
    "base-white": "#FFFFFF",
    "base-background": "#FAFAFA",
    "base-card": "#F3F2F2",
    "base-input": "#EDEDED",
    "base-button": "#E6E5E5",
    "base-hover": "#D7D5D5",
    "base-label": "#8D8686",
    "base-text": "#574F4D",
    "base-subtitle": "#403937",
    "base-title": "#272221",
    "base-error": "#f84747",
    "brand-purple-dark": "#4B2995",
    "brand-purple": "#8047F8",
    "brand-purple-light": "#EBE5F9",
    "brand-yellow-dark": "#C47F17",
    "brand-yellow": "#DBAC2C",
    "brand-yellow-light": "#F1E9C9",
  },
  textSizes: {
    "title-title-xl": "4.8rem",
    "title-title-l": "3.2rem",
    "title-title-m": "2.4rem",
    "title-title-s": "1.92rem",
    "title-title-xs": "1.8rem",
    "text-regular-l": "2rem",
    "text-bold-l": "2rem",
    "text-regular-m": "1.6rem",
    "text-bold-m": "1.6rem",
    "text-regular-s": "1.4rem",
    "text-bold-s": "1.2rem",
    "components-tag": "1rem",
    "components-button-g": "1.4rem",
    "components-button-s": "1.2rem",
  },
  fonts: {
    regular: "'Roboto'",
    title: "'Baloo 2'",
  },
};